server:
  port: 8005

eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka/

feign:
  hystrix:
    enabled: false
logging:
  level: info
spring:
  sleuth:
    sampler:
      percentage: 1.0
  zipkin:
    base-url: http://localhost:9004
  application:
    name: detail-c
#myorderprovider:
#  ribbon:
#    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RandomRule
